import turtle
tom=turtle.Turtle()
tom.speed(100)

def house():
    tom.color('black','grey')
    tom.begin_fill()
    for i in range(3):
        tom.forward(150)
        tom.left(120)
    tom.end_fill()
    tom.penup()
    tom.goto(25,15)
    tom.pendown()
    tom.color('black','orange')
    tom.begin_fill()
    for i in range(3):
        tom.forward(100)
        tom.left(120)
    tom.end_fill()
    tom.penup()

def move(tom,x,y):
    tom.penup()
    tom.goto(x,y)
    tom.pendown()

tom.color('black','brown')
tom.begin_fill()
tom.goto(25,40)
tom.pendown()
tom.left(90)
tom.forward(70)
tom.left(90)
tom.forward(20)
tom.left(90)
tom.forward(100)
tom.end_fill()
tom.color("black")
tom.goto(0,0)
tom.left(90)
house()
move(tom,0,0)
tom.left(-90)
tom.color('black','light gray')
tom.begin_fill()
tom.forward(200)
tom.left(90)
tom.forward(150)
tom.left(90)
tom.forward(200)
tom.end_fill()
move(tom,35,-200)
tom.color('black','light green')
tom.begin_fill()
for i in range(2):
    tom.forward(100)
    tom.right(90)
tom.forward(100)
tom.left(90)
tom.end_fill()
tom.color('black')
move(tom,105,-160)
tom.begin_fill()
tom.circle(5)
tom.end_fill()

move(tom,150,-200)
tom.color('black','light yellow')
tom.begin_fill()
for i in range(3):
    tom.forward(200)
    tom.left(90)
tom.end_fill()
tom.color('black','brown')
tom.begin_fill()

move(tom,350,0)
tom.left(90)
tom.left(105)
tom.forward(140)
tom.left(77)
tom.forward(245)
tom.end_fill()

tom.color('black','sky blue')
move(tom,200,-120)
tom.left(90)
tom.left(90)
tom.begin_fill()
for i in range(4):
    tom.forward(50)
    tom.left(90)
tom.end_fill()
tom.forward(25)
tom.left(90)
tom.forward(50)
move(tom,-100,200)
tom.color('black','yellow')
tom.begin_fill()
tom.circle(50)
tom.end_fill()
